# Python Object Mechanisms

## Builtin functions
For all objects
- str => implemented by `__str__`
- repr => implemented by `__repr__`
- type => implemented by attribute `__class__`
- help, ? => implmented by attribute `__doc__`

For some objects (cf notebook iterable/iterator)
- next => implemented by `__next__`
- iter => implemented by `__iter__`
- len => implemented by `__len__`

Hashable objects
- hash => implemented by `__hash__`

In [1]:
import numpy as np

In [9]:
data = np.random.normal(10.0, 2.5, 1_000_000)
print(data) # call builtin str => __str__

[17.21885099  8.03616455  7.91692342 ... 12.50038037  8.62060919
 11.81193395]


In [11]:
data # call builtin repr => __repr__

array([17.21885099,  8.03616455,  7.91692342, ..., 12.50038037,
        8.62060919, 11.81193395])

In [13]:
city = 'Toulouse'
print(str(city))
print(repr(city))

Toulouse
'Toulouse'


In [19]:
# default str and repr:
class City:
    pass

c = City()
print(c)
c

In [24]:
hash(123), hash('city')

(123, 315488702502446116)

In [26]:
x = 123

In [28]:
x.__hash__()

123

In [32]:
l = []
# hash(l) # TypeError: unhashable type: 'list'

In [40]:
l.__hash__ is None

True

## Operators
- `==` implemented by `__eq__`  (!= :  `__ne__`)
- order comparison (<, <=, >, >=): `__lt__, __le_, __gt__, __ge__`
- `+` implemented by `__add__` then `__radd__` (idem with `-, *, /, //, %, **`)
- `+=` implemented by `__iadd__` then `__add__` (idem with `-=, *=, /=, //=, %=, **=`)
- `[]`implemented by `__getitem__`, `__setitem__`
- operators bitwise: `&, |, ^, ~, <<, >>`
- `()` implemented by `__call__`

Nb: no overload for: `=, is, not, and, or`

In [105]:
11 / 3, 11 // 3, 11 % 3

(3.6666666666666665, 3, 2)

In [109]:
divmod(11, 3) # calls __divmod__

(3, 2)

In [46]:
print(x + 2)
print(x.__add__(2))

125
125


In [48]:
(1, 22, 3) + (55, 66)

(1, 22, 3, 55, 66)

In [50]:
"population: " + 77_000 

TypeError: can only concatenate str (not "int") to str

In [52]:
[1, 2, 3] + 4

TypeError: can only concatenate list (not "int") to list

In [58]:
iter([]) + 4

TypeError: unsupported operand type(s) for +: 'list_iterator' and 'int'

In [60]:
4 + iter([])

TypeError: unsupported operand type(s) for +: 'int' and 'list_iterator'

In [66]:
data + 4

array([21.21885099, 12.03616455, 11.91692342, ..., 16.50038037,
       12.62060919, 15.81193395])

In [70]:
data.__add__(4)

array([21.21885099, 12.03616455, 11.91692342, ..., 16.50038037,
       12.62060919, 15.81193395])

In [72]:
4 + data

array([21.21885099, 12.03616455, 11.91692342, ..., 16.50038037,
       12.62060919, 15.81193395])

In [74]:
x = 4
x.__add__(data)

NotImplemented

In [76]:
data.__radd__(4)

array([21.21885099, 12.03616455, 11.91692342, ..., 16.50038037,
       12.62060919, 15.81193395])

In [88]:
xi = 4
xf = 4.0
print(xi.__eq__(xf))
print(xf.__eq__(xi))
print(4 == 4.0)
print(4.0 == 4)

NotImplemented
True
True
True


In [92]:
data >= 20 # calls data.__ge__

array([False, False, False, ..., False, False, False])

In [96]:
data[data >= 20]  # calls  data.__getitem__

array([20.79794097, 20.15105978, 20.10642843, 20.14800016, 21.53307888,
       20.0368142 , 20.37606694, 20.56132111, 20.28434208, 21.39980996,
       20.37786576, 20.26987056, 20.21996826, 21.3160532 , 20.18190581,
       21.48312782, 20.43970547, 20.79283342, 20.94969176, 20.08784365,
       21.13534682, 20.06307223, 21.54056755, 20.39686174, 20.40435678,
       21.46646439, 20.03941674, 20.02475469, 20.66862518, 20.03160511,
       20.23520899, 20.28101488, 21.84913663, 20.10160598, 20.08355838])

In [113]:
# keep a reference on data
ref_data = data

# add inplace
data += 10
data

array([27.21885099, 18.03616455, 17.91692342, ..., 22.50038037,
       18.62060919, 21.81193395])

In [117]:
ref_data is data # same object in memory

True

In [119]:
data2 = data.copy()
data2 is data

False

In [121]:
data3 = data + 10
data3 is data

False

In [123]:
texte = "Toulouse"
ref_texte = texte
texte += ', ville rose'
texte

'Toulouse, ville rose'

In [125]:
texte is ref_texte

False

In [127]:
ref_texte

'Toulouse'

NB: pandas and numpy use 'element wise' overloads to combine filters, masks

In [156]:
data[(data < 9) | (data > 31)]

array([ 8.43580261, 31.53307888,  8.24646282, 31.39980996,  8.30851322,
       31.3160532 , 31.48312782, 31.13534682, 31.54056755,  8.27039065,
       31.46646439,  8.95002209,  8.36829615,  8.23718301, 31.84913663])

In [158]:
mask = (data < 9) | (data > 31)
data[mask]

array([ 8.43580261, 31.53307888,  8.24646282, 31.39980996,  8.30851322,
       31.3160532 , 31.48312782, 31.13534682, 31.54056755,  8.27039065,
       31.46646439,  8.95002209,  8.36829615,  8.23718301, 31.84913663])

In [160]:
data[~mask]

array([27.21885099, 18.03616455, 17.91692342, ..., 22.50038037,
       18.62060919, 21.81193395])

In [162]:
data_list = [ -1, 2, 4, 23, 10, 15 ]

In [168]:
[x for x in data_list if (x < 0) or (x > 20)]

[-1, 23]

In [174]:
all(x >= 0 for x in data_list)

False

In [176]:
any(x >= 0 for x in data_list)

True

In [180]:
np.any(data<10)

True

## Context manager: with
implemented by `__enter__`, `__exit__`

Examples: file, connection, cursor (open/close), pool thread (start/shutdown) , mutex (lock/unlock)


In [9]:
f = open('data/communes_france_2025.csv', encoding='UTF-8') # mode = 'rt'
f

<_io.TextIOWrapper name='data/communes_france_2025.csv' mode='r' encoding='UTF-8'>

In [10]:
 f.__enter__, f.__exit__

(<function TextIOWrapper.__enter__>, <function TextIOWrapper.__exit__>)

In [11]:
for _ in range(2):
    print(next(f))

,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,reg_code,reg_nom,dep_code,dep_nom,canton_code,canton_nom,epci_code,epci_nom,academie_code,academie_nom,code_postal,codes_postaux,zone_emploi,code_insee_centre_zone_emploi,code_unite_urbaine,nom_unite_urbaine,taille_unite_urbaine,type_commune_unite_urbaine,statut_commune_unite_urbaine,population,superficie_hectare,superficie_km2,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve

0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0108,Châtillon-sur-Chalaronne,200069193,CC de la Dombes,10,Lyon,01400,01400,08405,01053,01000,,

In [12]:
f.close()

In [20]:
with open('data/communes_france_2025.csv', encoding='UTF-8') as f:
    for _ in range(2):
        print(next(f))
# auto close: f.__exit__()

# check f is closed
assert f.closed

,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,reg_code,reg_nom,dep_code,dep_nom,canton_code,canton_nom,epci_code,epci_nom,academie_code,academie_nom,code_postal,codes_postaux,zone_emploi,code_insee_centre_zone_emploi,code_unite_urbaine,nom_unite_urbaine,taille_unite_urbaine,type_commune_unite_urbaine,statut_commune_unite_urbaine,population,superficie_hectare,superficie_km2,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve

0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0108,Châtillon-sur-Chalaronne,200069193,CC de la Dombes,10,Lyon,01400,01400,08405,01053,01000,,

In [21]:
# f.readline()
# ValueError: I/O operation on closed file.

In [22]:
with open('data/communes_france_2025.csv', encoding='UTF-8') as f:
    for _ in range(2):
        print(next(f))
    # emulate an error
    raise ValueError("something is wrong with this data")
    print("unreachable code")
# auto close: f.__exit__()

# exception can be handled later 

,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,reg_code,reg_nom,dep_code,dep_nom,canton_code,canton_nom,epci_code,epci_nom,academie_code,academie_nom,code_postal,codes_postaux,zone_emploi,code_insee_centre_zone_emploi,code_unite_urbaine,nom_unite_urbaine,taille_unite_urbaine,type_commune_unite_urbaine,statut_commune_unite_urbaine,population,superficie_hectare,superficie_km2,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve

0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0108,Châtillon-sur-Chalaronne,200069193,CC de la Dombes,10,Lyon,01400,01400,08405,01053,01000,,

ValueError: something is wrong with this data

In [23]:
assert f.closed

In [24]:
f = open('data/communes_france_2025.csv', encoding='UTF-8')
for _ in range(2):
    print(next(f))
# emulate an error
raise ValueError("something is wrong with this data")
print("unreachable code")
f.close()

,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,reg_code,reg_nom,dep_code,dep_nom,canton_code,canton_nom,epci_code,epci_nom,academie_code,academie_nom,code_postal,codes_postaux,zone_emploi,code_insee_centre_zone_emploi,code_unite_urbaine,nom_unite_urbaine,taille_unite_urbaine,type_commune_unite_urbaine,statut_commune_unite_urbaine,population,superficie_hectare,superficie_km2,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve

0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,84,Auvergne-Rhône-Alpes,01,Ain,0108,Châtillon-sur-Chalaronne,200069193,CC de la Dombes,10,Lyon,01400,01400,08405,01053,01000,,

ValueError: something is wrong with this data

In [25]:
assert not f.closed

In [33]:
class Resource:

    def __enter__(self):
        print("__enter__")


    def __exit__(self, exc_type, exc_value, traceback):
        print("__exit__")

In [34]:
with Resource() as r:
    print("Using resource:", r)
print("I'm done with this resource:", r)

__enter__
Using resource: None
__exit__
I'm done with this resource: None


In [35]:
with Resource() as r:
    print("Using resource:", r)
    raise ValueError("Pb!!!")
    print("Still using resource ??")
print("I'm done with this resource:", r)

__enter__
Using resource: None
__exit__


ValueError: Pb!!!

In [38]:
r = Resource()

In [39]:
r.__le__(r)

NotImplemented

## Operator as a function

In [40]:
import operator as op

In [41]:
data1 = [11, 22, 33]
data2 = range(3)

In [43]:
def compute(f, source1, source2):
    for a, b in zip(source1, source2):
        r = f(a, b)
        print(r)

In [45]:
compute(lambda x,y: (x + y)**2, data1, data2) 

121
529
1225


In [48]:
compute(op.add, data1, data2)

11
23
35


In [49]:
12 + 24

36

In [50]:
op.add(1, 2)

3

In [54]:
class MyFunction:
    def __call__(self):
        print("I'm a function !")

f = MyFunction()
f()

I'm a function !


In [56]:
MyFunction()()

I'm a function !
